### ISSUE TITLE
Add mosque search by Keywords (In addition by ID) on onboarding

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv#128]
**Onboarding screen and change mosque screens :**
Please add the mosque Search feature on onboarding in addition to the search by ID.
We need to have 2 separate fields : Search by ID and Search by Mosque name.

Also activate the geolocation permission to let users choose their nearest mosque.

Why? Because if we input the mosque ID in the mosque search, it could return results by Postal Code (as it's a numeric value).

**Comment by omar-cherif** [comment]
@ismaelAbogabal Here's the workflow that we would like to have :

> After selecting the language, the user arrives to a screen where we ask him:
**Do you know your 'mosque ID'?**
> 
> 1. If **Yes** : We display the current Mosque ID field whrere he can input it
> 2. If **No** : We display a mosque search screen (Similar to the mobile App) where he can geolocate the Mosque he's looking for, or simply search it by keywords.

**Comment by ismaelAbogabal** [comment]
Can you please provide the rest API routes for search by name and search by geo location.
