### ISSUE TITLE
Add support for the 'Mi TV Stick' 

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv#145]
The Mi TV Stick is becoming available worldwide, which is a great alternative te the Mi TV Box S. 

Both do have the same price (49,99€), but having this additional device is a must. Sometimes the Mi TV Box S isn't available. 

More info on the Mi TV Stick:
https://www.mi.com/fr/mi-tv-stick/#overview

**Comment by ismaelAbogabal** [comment]
app auto disconnects when mawaqit android tv launches on Mi stick

**Comment by omar-cherif** [comment]
I'm not sure I did understand your comment.

Could you please be more specific?

- How did you test?
- Expected behaviour
- How the test went?

**Comment by omar-cherif** [comment]
You can also share a video recording of the test session to help un understand the behaviour and the test results.
