### ISSUE TITLE
Add FLAG_KEEP_SCREEN_ON to prevent screen idle

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv#190]
Some users did report that some Android Box models go into sleep/idle mode. And they cannot change / or find this setting.
Please add FLAG_KEEP_SCREEN_ON 

More info: 
https://developer.android.com/reference/android/view/WindowManager.LayoutParams?authuser=2#FLAG_KEEP_SCREEN_ON

**Comment by ismaelAbogabal** [comment]
Flag is added and merged into code

**Comment by omar-cherif** [comment]
@ismaelAbogabal Could you please test the latest release (build 171) on the Mi Box S and confirm that it stays awake?

Of course you need to test the version from the Playstore, while keeping the default options of the box (do not enable developer options, annd keep the default settings of the box).

Also, please test on the other boxes and confirm the results per box.

Thanks.

**Comment by ismaelAbogabal** [comment]
Confirm wake lock is preventing the app from going into sleep mode 

## Test devices
- X96 MAX with (cortex-A53 processor) android 9 
- Mi box s 
- Mi stick 
- Chromecast 4th generation 
- Tevii p500 (cortex-A53 processor)

**Comment by omar-cherif** [comment]
Perfect!
Thank you for your confirmation !
