### ISSUE TITLE
Mobile version installed instead of TV verison on some boxes

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv#194]
A Xiaomi user did report yesterday that the App installing the mobile version instead of the TV version on Xiaomi Mi Box S.

@ismaelAbogabal could you please try and confirm if we still have this behavior?

Thanks

**Comment by omar-cherif** [comment]
![image](https://user-images.githubusercontent.com/33727630/184214743-046f3103-c12c-4992-bdd5-1612c592b9ca.png)

**Comment by omar-cherif** [comment]
@ismaelAbogabal Could you please test on different box models and confirm if it's solved or not yet? 

Thanks.

**Comment by ismaelAbogabal** [comment]
This issue is duplicated of #180
