### ISSUE TITLE
add CI

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv#8]
add github action CI 
code style check
build

**Comment by omar-cherif** [comment]
We will use for now the codemagic.io for the android-tv CI.
And we'll keep Github CI for mobile-app.

**Comment by ismael-abogabal-mawaqit** [comment]
We left the GitHub actions for the mobile app project.
We used Codemagic.io for CI/CD of the android tv project.

Codemagic is responsible for 
1- listening to GitHub pushes on main branch. 
2- building the app for release 
3- signing the app with key.jks
4- release the app on alpha track (internal testing) on google play console
